// src/lib/components/Board.svelte
<script lang="ts">
  import { deniedPlayingShakeAnimation, winningAnimation } from "$lib/animations.svelte";
  import { Mark } from "$lib/components";
  import { onTurnPVC } from "$lib/computer.svelte";
  import { playSoundFX } from "$lib/sound.svelte";
  import {
    type BoardIndex,
    getBoardState,
    getGameState,
    getWinner,
    NRO_CELLS,
    playerAction,
  } from "$lib/store.svelte";
  import { onMount } from "svelte";

  let board = $state<HTMLDivElement>();

  function boardAction() {
    playerAction().quickRestart();
  }

  function touchCell(bIdx: BoardIndex) {
    const { blocked } = playerAction(bIdx).placeMark();
    if (blocked) {
      const btnCells = document.querySelectorAll(".cell") as NodeListOf<HTMLElement>;

      for (let i = 0; i < NRO_CELLS; i++) {
        const cellNro = Number(btnCells[i].getAttribute("data-nro"));
        if (cellNro === bIdx) {
          console.log("shake", cellNro);
          deniedPlayingShakeAnimation(btnCells[i]);
        }
      }

      playSoundFX().denied();
      return;
    }

    playSoundFX().pop();
  }

  onMount(() => {
    playerAction().clearGame();
  });

  $effect(() => {
    if (board === undefined) return;

    if (getGameState() === "restarting") {
      board.addEventListener("click", boardAction);
    } else {
      board.removeEventListener("click", boardAction);
    }
  });

  $effect(() => {
    onTurnPVC();
  });

  $effect(() => {
    const winner = getWinner();
    if (winner !== null) {
      winningAnimation();
    }
  });
</script>

<div
  bind:this={board}
  class="mx-auto mt-20 grid aspect-square h-full w-full grid-cols-3 grid-rows-3 gap-[2.61%] rounded-[13%] bg-mantle p-[7.83%] shadow-xl shadow-neutral-600/5"
>
  {#each getBoardState() as cell, i}
    <button
      onclick={() => touchCell(i as BoardIndex)}
      data-nro={i}
      disabled={getGameState() === "restarting" || getGameState() === "cpu_thinking"}
      aria-disabled={getGameState() === "restarting" || getGameState() === "cpu_thinking"
        ? true
        : null}
      class="cell flex items-center justify-center rounded-[20%] bg-base-color p-[10%]"
      class:pointer-events-none={getGameState() === "restarting" ||
        getGameState() === "cpu_thinking"}
      class:pointer-events-auto={getGameState() !== "restarting" &&
        getGameState() !== "cpu_thinking"}
    >
      <Mark markState={cell.cell} player={cell.player} nro={i as BoardIndex} />
    </button>
  {/each}
</div>

// src/components/Board.vue
<script setup lang="ts">
import Mark from "./Mark.vue";
import { getBoardState, getCurrentPlayerTurnInPVC, getGameState, NRO_CELLS, playerAction } from "@/lib/store";
import { onUnmounted, watchEffect } from "vue";
import { onTurnPVC } from "@/lib/computer";
import { playSoundFX } from "@/lib/sound";

onUnmounted(() => {
  playerAction().clearGame();
});

watchEffect(() => {
  onTurnPVC();
});

function clickCell(index: number) {
  const { blocked } = playerAction().placeMark(index);

  if (blocked && getGameState.value === "restarting") {
    console.log("~ Go for quick restart");
    playerAction().quickRestart();
    playSoundFX().denied();
    return;
  }

  if (blocked) {
    console.log("Cell block!");
    const btnCells = document.querySelectorAll(".cell") as NodeListOf<HTMLElement>;

    for (let i = 0; i < NRO_CELLS; i++) {
      const cellNro = Number(btnCells[i]?.getAttribute("data-nro"));
      if (cellNro === index) {
        console.log("Shake Effect", cellNro);
      }
    }

    playSoundFX().denied();
    return;
  }

  playSoundFX().pop();
}
</script>

<template>
  <div
    class="bg-mantle mx-auto mt-20 grid aspect-square h-full w-full grid-cols-3 grid-rows-3 gap-[2.61%] rounded-[13%] p-[7.83%] shadow-xl shadow-neutral-600/5"
  >
    <button
      v-for="(cell, i) in getBoardState"
      :data-nro="i"
      :disabled="getCurrentPlayerTurnInPVC === 'computer'"
      :aria-disabled="getCurrentPlayerTurnInPVC === 'computer' ? true : false"
      class="cell bg-base-color flex items-center justify-center rounded-[20%] p-[10%]"
      :class="{
        'pointer-events-none': getCurrentPlayerTurnInPVC === 'computer',
        'pointer-events-auto': getCurrentPlayerTurnInPVC !== 'computer',
      }"
      @click="clickCell(i)"
    >
      <Mark :mark-state="cell.cell" :player="cell.player" :nro="i" />
    </button>
  </div>
</template>
